response = requests.get("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLHxYIqK7sMIutrKymkSEGQZq5l3odm_RxdI8i4_N3TrnN5wMAkQ&s")
img = Image.open(BytesIO(response.content)).convert("L")
plt.imshow(img)

img = img.resize((28,28))
img2 = np.array(img)
img2 = img2.reshape(1,784)
predictions = model.predict(img2)
#print(predictions)
print(np.argmax(predictions, axis=1))
